version: "3"
services:
  selenium:
    image: selenium/standalone-firefox:4.0.0
    ports:
      - "7901:7900"
      - "4444:4444"
    shm_size: 2gb

  bot:
    build:
      context: ./selenium_bot
    depends_on:
      - selenium
    links:
      - selenium
